[package]
name = "KIT-ILIAS-downloader"
version = "0.2.6"
authors = ["FliegendeWurst <2012gdwu@web.de>"]
license = "GPL-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.10.4", default-features = false, features = ["cookies", "gzip", "json", "rustls-tls", "stream"] }
tokio = { version = "0.2", features = ["full"] }
serde_json = "1.0.51"
scraper = "0.12.0"
url = "2.1.1"
futures-util = "0.3.4"
regex = "1.3.7"
lazy_static = "1.4.0"
parking_lot = "0.10.2"
structopt = "0.3.13"
rpassword = "4.0.5"
rprompt = "1.0.5"
ignore = "0.4.14"
anyhow = "1.0.28"
